name: Continuous Integration

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ make python3
    - name: Build library
      run: |
        cmake -S . -B build
        cmake --build build
    - name: Run tests
      run: ./build/bin/apto-test
